# Python segmentation benchmark

Make some test data for segmentation and test algorithm performance.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
%matplotlib inline

np.random.seed(12348)

# Set up constants

In [2]:
# duration stuff

T = 500  # total duration (in s)
dt = 0.05  # bin size (in s)
Nt = int(np.ceil(T / dt))

mu = 0.5  # mean state duration (in s)
sig = 0.05  # standard deviation of state duration (in s)

In [3]:
# rates
lam = 1.  # baseline rate (Hz)
nu = 500.  # rate multiplier (Hz)

# Make some intervals

In [4]:
durations = mu + sig * np.random.randn(Nt)
changepoints = np.cumsum(durations)
maxind = np.argwhere(changepoints > T)[0, 0]
changepoints = changepoints[:maxind]

In [5]:
changepoints / dt

array([   11.3095624 ,    19.66190965,    29.58543266, ...,  9972.56112388,
        9983.99454471,  9993.95774758])

In [6]:
taxis = np.arange(0, T, dt)
states = np.zeros(Nt)
rates = lam * np.ones(Nt)

In [7]:
for idx in xrange(0, len(changepoints), 2):
    if idx == len(changepoints) - 1:
        upper = T
    else:
        upper = changepoints[idx + 1]
    in_state_1 = (changepoints[idx] < taxis) & (taxis < upper)
    states[in_state_1] = 1
    rates[in_state_1] = nu * lam

# Make counts

In [8]:
counts = stats.poisson.rvs(rates * dt)

# Run inference

In [9]:
from spiketopics import pelt

In [10]:
cplist = pelt.find_changepoints(counts, lam, nu, dt, 2.)

# now time without jit overhead
%time cplist = pelt.find_changepoints(counts, lam, nu, dt, 2.)

CPU times: user 116 ms, sys: 0 ns, total: 116 ms
Wall time: 116 ms


In [11]:
inferred = pelt.calc_state_probs(counts, cplist, lam, nu, dt)

In [12]:
changepoints / dt , np.array(cplist)

(array([   11.3095624 ,    19.66190965,    29.58543266, ...,  9972.56112388,
         9983.99454471,  9993.95774758]),
 array([   0,    1,    2, ..., 9997, 9998, 9999]))